### ISSUE TITLE
Interesting!

### ISSUE THREAD

**Issue by trusktr** [doodadjs/doodad-js#2]
I like to see how others are implementing public/protected/private, and this was interesting to see.

Here's version: https://github.com/trusktr/lowclass

An advantage of lowclass is that it doesn't require anything like `doodad.OutsideCallback`. Access scope is always isolated to the class code. I have many examples in the `tests` folder.

Cheers!

**Comment by doodadjs** [comment]
@trusktr Thanks for your input. I'm waiting for the private fields proposal and other proposals to further develop. Probably "doodad-js" will be reduced to ES6 class decorators, I don't know.
